id: codewind-sidecar
apiVersion: v2
version: 0.6.0
type: Che Plugin
name: CodewindPlugin
title: CodewindPlugin
description: Enables iterative development and deployment in Che
icon: https://raw.githubusercontent.com/eclipse/codewind-vscode/master/dev/res/img/codewind.png
publisher: eclipse
repository: https://github.com/eclipse/codewind-che-plugin
category: Other
firstPublicationDate: "2019-05-30"
latestUpdateDate: "2019-10-10"
spec:
  containers:
  - name: codewind-che-sidecar
    image: tobespc/codewind-che-sidecar:0.6.0
    volumes:
      - mountPath: "/projects"
        name: projects
    ports:
      - exposedPort: 9090
